### ISSUE TITLE
 The inbreeding coefficients is negative

### ISSUE THREAD

**Issue by Zpengfei3236** [AlphaGenes/alphamate#1]
My simulation data has 1,030 individuals, included 30 sire and 1,000 dam. First, I run the program and got the results, but the value of the current inbreeding is -0.00028. Among the other outputs, the inbreeding and coancestry are also negative. As we know, the range of the inbreeding coefficients is from 0 to 0.5. Why is the inbreeding coefficients negative? Second, Won't the software give the value of genetic gain? Need us to calculate separately?

**Comment by gregorgorjanc** [comment]
Hi @Zpengfei3236 thanks for asking the question here. It would be useful to show some of the output so I can comment more precisely. But, I assume you use a genomic relationship matrix. Depending on how you have calculated the genomic relationship matrix, it is possible for the inbreeding (and relationship) coefficients to be negative. This means that the animals are less inbred (related) than the current mean of population. If your current mean inbreeding (relationship) is less than zero then again this depends on how you constructed the matrix. if your new/expected/future inbreeding is negative this suggests that AlphaMate found such parents that are less related than the current mean and then we expect that future inbreeding will be less than now.

**Comment by gregorgorjanc** [comment]
@Zpengfei3236 I am not clear about your issue with genetic gain. Can you elaborate? Perhaps show your spec file and output?

**Comment by Zpengfei3236** [comment]
[AlphaMateSpec.txt](https://github.com/AlphaGenes/alphamate/files/6230046/AlphaMateSpec.txt)
[Nrm.txt](https://github.com/AlphaGenes/alphamate/files/6230057/Nrm.txt)
[Targets.txt](https://github.com/AlphaGenes/alphamate/files/6230134/Targets.txt)
[OptimisationLogModeOptTarget1.txt](https://github.com/AlphaGenes/alphamate/files/6230137/OptimisationLogModeOptTarget1.txt)
[InbreedingSummary.txt](https://github.com/AlphaGenes/alphamate/files/6230138/InbreedingSummary.txt)

Thank you very much for your answer. My genomic relationship matrix was built by using the amat. pieces function in the R package GenomicMating. So, do I need to reconstruct the genomic relationship matrix in a different way? In the standard file, I set the weight of inbreeding to 0.5, so as to increase the inbreeding coefficients of the population and avoid negative value. I want to know what the genetic gain of the offspring is and whether it has been improved. However, I did not find the value of the genetic gain in the output file, so I would like to ask whether we need to calculate the genetic progress separately.

**Comment by gregorgorjanc** [comment]
@Zpengfei3236 There are many ways to build a genomic relationship matrix. Which genomic relationship matrix is best for OCS is debatable and very much a research question - see for example 

Management of Genetic Diversity in the Era of Genomics
https://www.frontiersin.org/articles/10.3389/fgene.2020.00880/full

Could you share the output you get on your screen and I can walk you over what is happening.

**Comment by Zpengfei3236** [comment]
[outputs.txt](https://github.com/AlphaGenes/alphamate/files/6233276/outputs.txt)
@gregorgorjanc Thanks for your sharing. I will read it carefully. This is the output on my screen.

**Comment by gregorgorjanc** [comment]
@Zpengfei3236 I was go through specific parts of the output and give comments.

Please note this:

`NOTE: Positive weight for targeted inbreeding, i.e., encourage higher inbreeding. Was this intended?`

` Current coancestry (average identity of the four genome combinations of two individuals)

  - coancestry among/between individuals
                     Among     Between
    - n:           1060900     1059870
    - average:    -0.00000    -0.00048
    - st.dev.:     0.02803     0.02333
    - minimum:    -0.04696    -0.04696
    - maximum:     0.62554     0.36694
    Among   = coancestry among   individuals (including self-coancestry) = expected inbreeding in their progeny under random mating, including selfing
    Between = coancestry between individuals (excluding self-coancestry) = expected inbreeding in their progeny under random mating, excluding selfing
`

You see here that you have some negative coancestries as I have mentioned before. This is OK for genomic coancestries (=0.5*relationships)

` Current inbreeding (identity between the two genomes of an individual)
  - n:              1030
  - average:    -0.00284
  - st.dev.:     0.02802
  - minimum:    -0.06604
  - maximum:     0.25107`

And similarly for inbreeding. This is OK for genomic estimate of inbreeding.

`Optimise contributions for minimum future coancestry (ModeMinCoancestry) ...`

Here AlphaMate is searching for contributions (and mating plan if that is what you asked for) that would minimise future coancestry

`Optimise contributions for minimum future inbreeding (ModeMinInbreeding) ...`

Here AlphaMate is searching for contributions (and mating plan if that is what you asked for) that would minimise future inbreeding

`Optimise contributions for maximum future selection criterion (ModeMaxCriterion) ...`

Here AlphaMate is searching for contributions (and mating plan if that is what you asked for) that would maximise genetic gain

`Optimise contributions for maximum future selection criterion with constraint on coancestry (and inbreeding) ...`

Here AlphaMate is searching for contributions (and mating plan if that is what you asked for) that would satisfy targets you  have defined. And you see what individuals are selected and what rates of coancestry and inbreeding you can expect.

What is puzzling you about the genetic gain at this stage?

**Comment by Zpengfei3236** [comment]
Thank you for your answer. I want to observe the change of genetic gain and inbreeding coefficients of multiple generations of population after genomic mating. My desired goal is to maximize genetic gain with the constrained loss of genetic diversity or inbreeding coefficients. 
The reason I set the inbreeding weight to 0.5 is to avoid having negative inbreeding coefficients in the result. Because, by default, the inbreeding coefficient in the result is negative. I think the minimum coefficients is 0 and I want to keep the average inbreeding coefficient between 0 and 0.06. The value of inbreeding coefficient is negative, which is what puzzles me. I'm going to rebuild the genome relationship matrix in another way and try again.
About genetic gain, I didn't find specific genetic gain values in the output file. I want to know how much genetic progress has changed in the offspring population if I use the mating plan to maximize genetic progress. Is there a specific value of genetic gain in the output, or do we need to calculate it separately?

**Comment by gregorgorjanc** [comment]
@Zpengfei3236 negative inbreeding is ok - it means you have less inbreeding than expected on average. To see this let's look at various optimisations mentioned above.

```
Optimise contributions for minimum future coancestry (ModeMinCoancestry) ...
  Iteration  AcceptPct  Objective  Penalties     Degree  SelCriter     ...Std     ...Pct Coancestry    ...Rate     ...Pct Inbreeding    ...Rate     ...Pct
          0        NaN   -0.00476    0.00000        NaN    0.26009    0.82963        NaN    0.00476    0.00476        NaN   -0.00000    0.00282        NaN
        200        4.2   -0.00445    0.00000        NaN    0.25846    0.81851        NaN    0.00445    0.00445        NaN   -0.00116    0.00167        NaN
```

Here AlphaMate is searching for contributions (and mating plan if that is what you asked for) that would minimise future coancestry. It came up with the coancestry rate of 0.00445, which also gives an inbreeding rate of 0.00167 (note that inbreeding was negative for the selected individuals -0.00116, but since the starting inbreeding (for all selection candidates) was on average -0.00284 (less than -0.00116) we get a positive rate); and mean selection criterion of selected individuals 0.25.

```
Optimise contributions for minimum future inbreeding (ModeMinInbreeding) ...
  Iteration  AcceptPct  Objective  Penalties     Degree  SelCriter     ...Std     ...Pct Coancestry    ...Rate     ...Pct Inbreeding    ...Rate     ...Pct
          0        NaN   -0.00023    0.00000        NaN    0.25962    0.82647        NaN    0.00500    0.00500        NaN   -0.00260    0.00023        NaN
        400        4.2    0.00461    0.00000        NaN    0.26082    0.83461        NaN    0.00960    0.00960        NaN   -0.00746   -0.00461        NaN
```

Similar here, but here AlphaMate minimised inbreeding instead of coancestries. AlphaMate found contributions that give negative rate of inbreeding - the selected individuals had lower inbreeding (-0.00746) than the average inbreeding of all individuals (-0.00284).

```
Optimise contributions for maximum future selection criterion (ModeMaxCriterion) ...
  Iteration  AcceptPct  Objective  Penalties     Degree  SelCriter     ...Std     ...Pct Coancestry    ...Rate     ...Pct Inbreeding    ...Rate     ...Pct
          0        NaN    1.55861    0.00000        NaN    0.26312    0.85029        NaN    0.00509    0.00509        NaN   -0.00095    0.00188        NaN
        200       94.0    2.34522    0.00000        NaN    0.32617    1.27942        NaN    0.14862    0.14862        NaN   -0.00077    0.00206        NaN
```

Maximising only selection criterion gave us average of 0.32 in selected individuals. This is 1.27 standard deviations above the mean. This is the most gain you can achieve - without constraints.

```
Optimise contributions for maximum future selection criterion with constraint on coancestry (and inbreeding) ...
  Iteration  AcceptPct  Objective  Penalties     Degree  SelCriter     ...Std     ...Pct Coancestry    ...Rate     ...Pct Inbreeding    ...Rate     ...Pct
          0        NaN    0.74768    0.00000       87.1    0.26192    0.84210        5.1    0.00508    0.00508       99.6    0.00172    0.00454      -37.2
       3300        4.0    3.87698    0.00000       83.6    0.26580    0.86849       10.8    0.00954    0.00954       96.5    0.03313    0.03587     -506.5
```

This is now multi-objective optimisation and I note you have very little expected genetic gain - you have likely set your targets rather strictly. I also note that you are at the same time trying to get more genetic gain, constrain coancestry and INCREASE inbreeding. Since coancestry and inbreeding are highly correlated, AlphaMate will struggle to find something meaningful.

**Comment by Zpengfei3236** [comment]
Thank you for your detailed answer. Does "objective" mean genetic gain? 
I noticed the function “Modeopt” can maximizes standardized genetic gain with on Group coancestry and potentially other targets. I also want to use “modeopt” and “evaluatefrontier” to get Pareto optimal solutions, so as to maximize genetic gain and control inbreeding coefficient. 
Therefore, if I use the function “Modeopt” to do multi-objective optimization, do I need to adjust the setting of TargetDegree to achieve better results?

**Comment by gregorgorjanc** [comment]
Objective varies depending on the optimisation type. We are always trying to increase the value of objective, but it means different things in different types of optimisations. Take time and study your output.

`evaluatefrontier` is the same as `modeopt`, but instead of doing just one multi-objective target (as you had above with one value for degree) it explores the full frontier of targets.

**Comment by gregorgorjanc** [comment]
@Zpengfei3236 in terms of "achieving better results" you need to ask yourself what you want and then see how AlphaMate optimisations align with this. For example, you most likely don't want to increase inbreeding (there are some applications where you would want that).

**Comment by Zpengfei3236** [comment]
Thank you for your kind help. I will study it carefully and combine with your opinions, Hope to have more opportunities to communicate with you in the future. Again, really appreciate your help!
